global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 1 second. The default is every 1 minute.


scrape_configs:
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:8094']

  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
 
    static_configs:
      - targets: ['localhost:9323']